Continuous Deployment for development branch
AAU-ASE-GroupC-WS2021/canteenMgmtFrontend pull request #25
Opened 2022-01-23 13:18 UTC by madmini

Enables CD to GitHub Pages for branch `development`. Includes improvements and fixes for the deployment script.

To verify that this is functional, see CircleCI pipeline runs simulated for [main](https://app.circleci.com/pipelines/github/AAU-ASE-GroupC-WS2021/canteenMgmtFrontend/69/workflows/0616d14c-1029-4527-8771-675c80b20111/jobs/239?invite=true&invite=true&invite=true#step-108-41) (deploys to [aau-ase-groupc-ws2021.github.io](https://aau-ase-groupc-ws2021.github.io/), see [repo](https://github.com/AAU-ASE-GroupC-WS2021/AAU-ASE-GroupC-WS2021.github.io)) and [development](https://app.circleci.com/pipelines/github/AAU-ASE-GroupC-WS2021/canteenMgmtFrontend/69/workflows/f01f5148-746f-4cf9-983c-8dd2163cd54b/jobs/235?invite=true#step-108-41) (deploys to [aau-ase-groupc-ws2021.github.io/frontend_dev_pages](https://aau-ase-groupc-ws2021.github.io/frontend_dev_pages/), see [repo](https://github.com/AAU-ASE-GroupC-WS2021/frontend_dev_pages)).
Note: both pipelines were run on the second-to-last commit at the time of writing, as the most recent commit (50245f72124f49c604d32a5d0363b0c80db32c08) disables the workflow for this branch (was enabled for testing purposes).

CircleCI setup: As [recommended by CircleCI](https://circleci.com/docs/2.0/gh-bb-integration/#controlling-access-via-a-machine-user) for complex deploy-key setups, a GitHub ["machine user"](https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users) ([canteen-frontend-deploy-machine-user](https://github.com/canteen-frontend-deploy-machine-user)) was set up and added as collaborator to both GitHub Pages repos and the frontend repo (necessary for generating a deploy key used in the CircleCI frontend pipeline).

2022-01-23 14:33 UTC, elsantner requested changes
Currently not working correctly:
`https://aau-ase-groupc-ws2021.github.io/frontend_dev_pages/` (**dev domain**) redirects to `https://aau-ase-groupc-ws2021.github.io/#/` (**production domain**).

2022-01-23 22:14 UTC, madmini commented
@elsantner I believe now that this is flutter web being not configured correctly.
Comments in [`web/index.html`](https://github.com/AAU-ASE-GroupC-WS2021/canteenMgmtFrontend/blob/b2a89d31cb5ecb98a8ad60897b1956395d74ecf6/web/index.html#L14) mention the `--base-href` build argument which allows specifying the path prefix.
I also believe the application would have worked, and redirect from dev to prod only when the page is reloaded manually.

In any case, to avoid confusion and for robustness, I have changed the deployment targets to not have potentially overlapping urls.

2022-01-23 22:24 UTC, elsantner approved these changes

2022-01-24 21:32 UTC, elsantner approved these changes
Everything looks good to me. 
I didn't test the deployment scripts but from the deployed versions I trust that they work.
The new run configurations and about button also work as expected.
Overall very well done - thank you for your efforts!

2022-01-24 21:37 UTC, merged